# Server address information
app:
  address:
    host: 127.0.0.1
    port: 5000

# If true, teleoperate a mobile robot in Gazebo simulator
use_sim: false

# Names of the topics and services of the real Husarion Panther mobile robot.
robot:
  services:
    e_stop_reset: /panther/hardware/e_stop_reset
    e_stop_trigger: /panther/hardware/e_stop_trigger
  topics:
    battery_status: /panther/battery/battery_status
    camera: /zed_rear/zed_node_1/rgb/color/rect/image
    e_stop: /panther/hardware/e_stop
    odom: /fixposition/odometry_enu_smooth
    nav_feedback: /navigate_to_pose/_action/feedback
    navsatfix: /fixposition/odometry_llh
    planned_path: /plan
    teleop: /panther/cmd_vel

# Names of the topics and servives of the mobile robot in Gazebo simulator.
sim:
  services:
    e_stop_reset: 
    e_stop_trigger:  
  topics:
    battery_status: 
    camera: /camera/front/image_raw
    e_stop: 
    odom: /odometry/global
    nav_feedback: /navigate_to_pose/_action/feedback
    navsatfix: /gps/fix
    planned_path: /plan
    teleop: /cmd_vel